[Refactor] Move ZMLocalNotification class from SE
wireapp/wire-ios-request-strategy pull request #240
Opened 2020-08-26 09:21 UTC by KaterinaWire

## What's new in this PR?

To be able to convert an update event to a localNotification in `Notification engine`, we need to have `ZMLocalNotification` in the `Request strategy`. This PR contains ZMLocalNotification and all required classes are moved from SE.

2020-08-26 15:10 UTC, typfel commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
Why did you add AVS as dependency?

2020-08-26 15:16 UTC, typfel commented
All test classes haven't been moved like: LocalNotificationDispatcherTests

2020-08-26 15:22 UTC, typfel commented on Sources/Notifications/Push Notifications/LocalNotificationDispatcher.swift
> +@objcMembers public class LocalNotificationDispatcher: NSObject {
Do you really need to move the `LocalNotificationDispatcher`?

2020-08-26 16:41 UTC, billypchan commented
We need to rewrite pipeline to download Crowdin string resource after this PR is merger.

2020-08-26 17:11 UTC, KaterinaWire commented on Sources/Notifications/Push Notifications/LocalNotificationDispatcher.swift
> +@objcMembers public class LocalNotificationDispatcher: NSObject {
No, I removed it.

2020-08-26 17:11 UTC, KaterinaWire commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
Because I moved `CallClosedReason`

2020-08-26 19:19 UTC, typfel approved these changes

2020-08-27 07:21 UTC, KaterinaWire commented
> We need to rewrite pipeline to download Crowdin string resource after this PR is merger.

I will do it when I merge this PR to the develop branch.

2020-08-27 08:45 UTC, johnxnguyen requested changes
There have been some changes to this code on Sync Engine which aren't present here. Don't forget to include them.

2020-08-27 08:45 UTC, johnxnguyen commented on Sources/Notifications/Push Notifications/Notification Types/LocalNotificationType+Configuration.swift
> +            }
This seems to be out of date with the latest sync engine release.

2020-08-27 08:45 UTC, johnxnguyen commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
But do you need AVS or just the enum? I suggest to try to see if you can extract what you need for notifications away from the AVS library.

2020-08-27 12:36 UTC, KaterinaWire commented on Sources/Notifications/Push Notifications/Notification Types/LocalNotificationType+Configuration.swift
> +            }
Updated

2020-08-27 12:39 UTC, KaterinaWire commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
Right now yes. But the next step will be to handle call notifications in notification service extension, and we need to move more  classes to the request strategy related to the calling.

2020-08-27 14:00 UTC, johnxnguyen commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
Which calling related classes do you need to move?

2020-08-28 06:38 UTC, typfel commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
We will need figure out if we have a incoming call in the notification engine, it means we'll need to forward events to AVS and listen to their callbacks. Either we need to split that part out of the CallingRequestStrategy and WireCallCenter or build something new for the notification engine.

What do think @johnxnguyen ?

2020-08-28 07:00 UTC, johnxnguyen commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
So we need to

- process a call message event, pass it to AVS
- AVS will invoke the incoming call handler
- `WireCallCenter` will broadcast a new incoming call state
- `CallStateObserver` responds to the state change and tells the `LocalNotificationDispatcher` to make the local notification.

It doesn't make sense to move **all** of the calling code to the request strategy framework just so we can figure out if we need to display one type of notification (which is only going to happen if CallKit is disabled).

I'm hesitant to interface with AVS over two different frameworks, but it would probably be fine if in the notification engine AVS was used in an absolutely minimal and isolated way.

So the notification engine sits next to sync engine and share engine? That is, between the UI and request strategy?

2020-08-28 07:09 UTC, typfel commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
> So the notification engine sits next to sync engine and share engine? That is, between the UI and request strategy?

Exactly

> It doesn't make sense to move all of the calling code to the request strategy framework just so we can figure out if we need to display one type of notification (which is only going to happen if CallKit is disabled).

No, maybe it make sense to re-implement this use case in the notification engine.

2020-08-28 07:28 UTC, johnxnguyen commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
If we re-implement this use case in the notification engine, then we would have two instances of AVS, one that would be run while the app is in the foreground, and the other run in the notification extension while the main app is in the background (is this correct?). This would mean that if we opened the app to answer the call, the foreground instance of AVS wouldn't know there was an incoming call.

2020-08-28 07:35 UTC, typfel commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
As described here https://github.com/wireapp/ios-architecture/issues/90

The idea is that we will process the call events in notification extension in order figure out if there's an incoming call so that we can display a calling notification / notify CallKit. We are not deleting any events in the notification extension, that means we will process same calling events again when the main app is launched. That way AVS will be up to date on the call state.

This works because AVS is not persisting any call state, it's only kept in memory.

2020-08-28 07:49 UTC, johnxnguyen commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
Great, thanks for explanation. I would see what this miniature call center would look like, if it's compact and concise then it would suitable. But it could be that it doesn't make so much sense in which case we should find another solution.

Already thinking about it, I can see that creating a new instance of AVS would require us to register a lot of callbacks that would never get used. This would lead to a lot of unnecessary duplication.

2020-08-28 08:31 UTC, typfel commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
> Already thinking about it, I can see that creating a new instance of AVS would require us to register a lot of callbacks that would never get used. This would lead to a lot of unnecessary duplication.

Mm maybe the `AVSWrapper` could be shared if it's decoupled from the `WireCallCenter`

2020-08-31 06:34 UTC, KaterinaWire commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
@johnxnguyen Could it be a temporary solution to move `CallClosedReason` and add AVS s a dependency to the request strategy? And I can add a ticket (as a reminder) to discuss/refactor the calling events.

2020-08-31 06:53 UTC, johnxnguyen commented on Cartfile.resolved
> +github "wireapp/avs-ios-binaries" "6.0.223"
Sure, but we should try to understand what the proper solution to this will be as it may require a bit of work.

2020-09-03 09:24 UTC, merged