[Feature] Define the basic interface for feature controller
wireapp/wire-ios-request-strategy pull request #254
Opened 2020-11-17 07:30 UTC by KaterinaWire

## What's new in this PR?

### Issues
Add a FeatureController that is responsible for :
- parse and save configs to the Core Data,
- notify UI (Applock) / features.

Needs releases with:

- https://github.com/wireapp/wire-ios-data-model/pull/1066
- https://github.com/wireapp/wire-ios-data-model/pull/1067

### Attachments
https://miro.com/app/board/o9J_lfiqql4=/

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +public enum FeatureModel {
I think we should find a more suitable name, but not quite sure what just yet.

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    var status: String
The value of `status` is always expected to be `enabled` or `disabled`, right? In this case, we could define and use an enum:

```swift
enum Status: String, Codable {
  case enabled
  case disabled
}
```

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    }
I suggest to use the `Status` enum I mentioned earlier as the return type because it would read better and make more sense. E.g what does this mean? `if status(for: AppLock.self) { ... }`

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    }
All features have a status, but not all features are configurable. The type constraint here only returns the status for configurable features. Not a major issue now since we only have one feature and it is configurable, but it would be a problem.

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +        return try? JSONDecoder().decode(feature.Config, from: configData)
I suggest to use the generic parameter directly instead of the argument, for readability sake. I.e `T.name` instead of `feature.name` and `T.Config` instead of `feature.Config`.

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +// MARK: - Internal
This says internal but the methods are public.

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +            let configuration = try JSONDecoder().decode(FeatureConfigResponse<FeatureModel.AppLock>.self, from: data)
The `feature` argument isn't being used, do you mean to write this?

```swift
try JSONDecoder().decode(FeatureConfigResponse<T>.self, from: data)
```

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +            }
Are you planning to generalize this in a later PR? If so, add a todo comment with your name so we don't forget.

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +        } catch {}
We should in the very least log the failure so we can become aware of decoding issues.

2020-11-17 08:46 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +            self = false
The `Status` enum would make this redundant.

2020-11-17 08:46 UTC, johnxnguyen commented on Tests/Helpers/FeatureControllerTest.swift
> +        let data = try? JSONSerialization.data(withJSONObject: json, options: JSONSerialization.WritingOptions.prettyPrinted)
You could also write the json object as a string (which is cleaner in my opinion):

```swift
let json = """
{
  "applock": {
      "status": "disabled",
      ...
    }
}
"""

let data = json.data(using: .utf8)!
```

2020-11-17 08:46 UTC, johnxnguyen commented on Tests/Helpers/FeatureControllerTest.swift
> +        let featureStatus = sut.status(for: FeatureModel.AppLock.self)
Since we're testing the save method, we should check the database directly instead of fetching the status. Testing the status method should be done in a separate test.

2020-11-17 11:36 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +public enum FeatureModel {
Yes, I didn't want to have the same name as a Core Data entity.
`FeatureType` ?

2020-11-17 11:36 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    var status: String
Done.
I added this enum to DM and changed the name to `FeatureStatus` because it will be public and we might have other statuses.
Feature class in the DM now has a status property with this type.

2020-11-17 11:36 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    }
Changed the return value type.

We can make all the next features configurable, but without any configuration.
E.g.
```
public enum DigitalSignature: Configurable {
        public static var name: String = "digital-signature"
        public struct Config: Codable {
        }
    }
```

2020-11-17 11:36 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +        return try? JSONDecoder().decode(feature.Config, from: configData)
Done

2020-11-17 11:36 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +// MARK: - Internal
Fixed

2020-11-17 11:36 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +            let configuration = try JSONDecoder().decode(FeatureConfigResponse<FeatureModel.AppLock>.self, from: data)
Yes. 
Fixed

2020-11-17 11:37 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +            }
Added comment

2020-11-17 11:37 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +        } catch {}
Added logs

2020-11-17 11:37 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +            self = false
Removed

2020-11-17 11:52 UTC, KaterinaWire commented on Tests/Helpers/FeatureControllerTest.swift
> +        let featureStatus = sut.status(for: FeatureModel.AppLock.self)
Fixed

2020-11-17 11:52 UTC, KaterinaWire commented on Tests/Helpers/FeatureControllerTest.swift
> +        let data = try? JSONSerialization.data(withJSONObject: json, options: JSONSerialization.WritingOptions.prettyPrinted)
Done

2020-11-17 12:14 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    }
Just an idea: another way would be to split `Configurable` protocol into two:

```swift
protocol Configurable {
  typealias Config: Codable
}

protocol Named {
  static var name: String { get }
}

func status<T: Named>(for feature: T.Type) -> FeatureStatus

2020-11-17 12:22 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +            zmLog.error("Failed to decode response: \(error)"); return
`return` is redundant.

2020-11-17 12:22 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +            zmLog.error("Failed to decode response: \(error)"); return
`return` is redundant.

2020-11-17 12:22 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +                                                        context: moc)
Needs formatting.

2020-11-17 12:22 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    public func save<T: Configurable>(_ feature: T.Type, data: Data) {
Is there a reason why we decode `data` here and not in the request strategy? To me I would expect the request strategy to handle decoding of response models.

2020-11-17 12:25 UTC, johnxnguyen requested changes

2020-11-17 12:25 UTC, johnxnguyen commented on Tests/Helpers/FeatureControllerTest.swift
> +        XCTAssertNotNil(fechedFeature)
It's worth asserting the values of `fetchedFeature`.

2020-11-17 12:25 UTC, johnxnguyen commented on Tests/Helpers/FeatureControllerTest.swift
> +        XCTAssertNotNil(fechedFeature)
Also here, assert the values of `fetchedFeature`.

2020-11-17 12:25 UTC, johnxnguyen commented on Tests/Helpers/FeatureControllerTest.swift
> +        let featureStatus = sut.status(for: FeatureModel.AppLock.self)
If the method you want to test is `status(for:)`, then it should be under "when".

2020-11-17 15:08 UTC, KaterinaWire commented on Tests/Helpers/FeatureControllerTest.swift
> +        let featureStatus = sut.status(for: FeatureModel.AppLock.self)
Fixed

2020-11-17 15:08 UTC, KaterinaWire commented on Tests/Helpers/FeatureControllerTest.swift
> +        XCTAssertNotNil(fechedFeature)
Added

2020-11-17 15:08 UTC, KaterinaWire commented on Tests/Helpers/FeatureControllerTest.swift
> +        XCTAssertNotNil(fechedFeature)
Added

2020-11-17 15:08 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +                                                        context: moc)
Fixed

2020-11-17 15:08 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +            zmLog.error("Failed to decode response: \(error)"); return
Removed

2020-11-17 15:08 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +            zmLog.error("Failed to decode response: \(error)"); return
Removed

2020-11-17 15:22 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    }
Yes, good idea.
But `Configurable` protocol should conform the `Named` protocol. When we save a feature, we should have access to the name and config.

2020-11-17 15:42 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    public func save<T: Configurable>(_ feature: T.Type, data: Data) {
To be honest I don't have a strong opinion about that. 
But if we decide to move it to the request strategy, that there is no need to keep "saving logic" inside the `FeatureController`. Currently we have access to `FeatureController` only from the request strategy.

2020-11-18 07:42 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    }
You can use protocol composition to combine them, e.g `Named & Configurable`.

2020-11-18 07:52 UTC, johnxnguyen commented on Tests/Helpers/FeatureControllerTest.swift
> +        let featureStatus = sut.status(for: FeatureModel.AppLock.self)
The test is that is fetches the status. So `sut.save` should be part of the "given" section. This clearly indicates exactly which methods are being tested.

2020-11-18 09:56 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    }
Changed to `Named & Configurable`

2020-11-18 09:58 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    public func save<T: Configurable>(_ feature: T.Type, data: Data) {
Moved data decoding to request strategy

2020-11-18 09:58 UTC, KaterinaWire commented on Tests/Helpers/FeatureControllerTest.swift
> +        let featureStatus = sut.status(for: FeatureModel.AppLock.self)
Done

2020-11-18 10:13 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +        guard let feature = Feature.fetch(T.name, context: context) else {
Don't forget to switch the contexts queue, otherwise you'll get a crash. Something like:

```swift
context.performBlockAndWait {
  ...
}
```

2020-11-18 10:13 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    public func configuration<T: Configurable & Named>(for feature: T.Type) -> T.Config? {
Would this also need to be static?

2020-11-18 10:13 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    public func save<T: Configurable & Named>(_ feature: T.Type, configuration: FeatureConfigResponse<T>) {
Does this need to be public? If only the request strategy will call it then better to keep it internal.

2020-11-18 10:13 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +    public func saveAllFeatures(_ configurations: AllFeatureConfigsResponse) {
Does this need to be public? If only the request strategy will call it then better to keep it internal.

2020-11-18 11:32 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    public func saveAllFeatures(_ configurations: AllFeatureConfigsResponse) {
No, there is no need to make it public. 
Changed it

2020-11-18 11:32 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    public func save<T: Configurable & Named>(_ feature: T.Type, configuration: FeatureConfigResponse<T>) {
Changed it to internal

2020-11-18 11:32 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +    public func configuration<T: Configurable & Named>(for feature: T.Type) -> T.Config? {
Yes.
Changed

2020-11-18 12:27 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +        guard let feature = Feature.fetch(T.name, context: context) else {
Why will be crash?

2020-11-18 14:50 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +public enum FeatureModel {
I guess the right name it would be `Feature` but to don't create confusion with the DM another option would be `FeatureObject`. It is just a suggestion

2020-11-18 14:53 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +                case enforceAppLock = "enforceAppLock"
For the CodingKeys when the rawValue is equal to the key it is not necessary to specify it there. This could become 

```swift
private enum CodingKeys: String, CodingKey {
           case enforceAppLock
           case inactivityTimeoutSecs
 }
```

2020-11-18 14:54 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +                case enforceAppLock = "enforceAppLock"
Basically for the `FeatureConfigResponse` is done as I meant in the previous comment.

2020-11-18 14:56 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +import Foundation
General thought: I would add more pragma mark to separate the code in this class.

2020-11-18 14:59 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +        // TODO: Katerina make it more general for all features
Thanks Katerina :-D. 💯

2020-11-18 15:04 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +public struct AllFeatureConfigsResponse: Decodable {
Why don't call it just `FeatureConfigsResponse` and remove the prefix `all`. But if @johnxnguyen approves this naming means that it is better.

2020-11-18 15:08 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +        let appLockFeature = Feature.createOrUpdate(appLock.name,
Here you can use the method you created on top `func save<T: Configurable & Named>`  so you can remove the duplicated `Feature.createOrUpdate(...`

2020-11-18 16:26 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +        let appLockFeature = Feature.createOrUpdate(appLock.name,
Yes, I could, but I need to post a notification with a `appLockFeature` inside the `userInfo`.
Currently `func save<T: Configurable & Named>`doesn't return the value.

2020-11-18 16:41 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +                case enforceAppLock = "enforceAppLock"
Yes, good point.

2020-11-19 07:57 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +public enum FeatureModel {
Well, maybe we could simply move the contents of `FeatureModel` into an extension for `Feature`. The only purpose of the `FeatureModel` enum is to provide a namespace for the phantom types. `Feature` is a suitable name and the data model class is closely related to the phantom types so I don't see a problem with using it as a namespace. Thoughts?

2020-11-19 08:01 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +        guard let feature = Feature.fetch(T.name, context: context) else {
Every managed object context is associated with a thread. The ui context runs on the main thread, and all other contexts run on their own private background thread. If you work with a context on a different thread Core Data will crash your app. It's part of the concurrency model for Core Data. You can read more about it [here](https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext)

2020-11-19 08:02 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +import Foundation
Adding to this, I would even go as far as to separate it into separate files 😄

2020-11-19 08:05 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +public struct AllFeatureConfigsResponse: Decodable {
I suggested to add the "all" prefix to make it easier to spot the difference:

```swift
FeatureConfigResponse
FeatureConfigsResponse
```

vs

```swift
FeatureConfigResponse
AllFeatureConfigsResponse
```

2020-11-19 08:08 UTC, johnxnguyen commented on Sources/Helpers/FeatureController.swift
> +                case enforceAppLock = "enforceAppLock"
It is also unnecessary to define `CodingKeys` if the cases match the property names, the compiler will synthesize this for you.

2020-11-19 09:32 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +public struct AllFeatureConfigsResponse: Decodable {
Ok, mine was just a thought :-)

2020-11-19 09:32 UTC, marcomaddy1982 commented on Sources/Helpers/FeatureController.swift
> +public enum FeatureModel {
Make sense!!!

2020-11-19 09:34 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +                case enforceAppLock = "enforceAppLock"
Removed CodingKeys

2020-11-19 09:35 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +        guard let feature = Feature.fetch(T.name, context: context) else {
Done

2020-11-19 09:51 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +public enum FeatureModel {
Good idea. 
Moved `AppLock enum` to the  `Feature` extension.

2020-11-19 09:52 UTC, KaterinaWire commented on Sources/Helpers/FeatureController.swift
> +import Foundation
Make sense.

2020-11-19 11:01 UTC, marcomaddy1982 approved these changes

2020-11-19 12:31 UTC, johnxnguyen commented on Sources/Helpers/FeatureConfiguration/Configurations.swift
> +public struct FeatureConfigResponse<T: Configurable>: Decodable {
Does this need to be public?

2020-11-19 12:31 UTC, johnxnguyen commented on Sources/Helpers/FeatureConfiguration/Configurations.swift
> +public struct AllFeatureConfigsResponse: Decodable {
Does this need to be public?

2020-11-19 12:31 UTC, johnxnguyen commented on Sources/Helpers/FeatureConfiguration/FeatureController.swift
> +    }
Does this need to be public?

2020-11-19 12:31 UTC, johnxnguyen commented on Sources/Helpers/FeatureConfiguration/FeatureController.swift
> +    public static let needsToUpdateFeatureNotificationName = Notification.Name("needsToUpdateFeatureConfiguration")
I think a better name would be something like `FeatureConfigDidChange`.

2020-11-19 12:31 UTC, johnxnguyen commented on Tests/Helpers/FeatureControllerTest.swift
> +}
Missing a test for fetching a config.

2020-11-19 13:06 UTC, KaterinaWire commented on Tests/Helpers/FeatureControllerTest.swift
> +}
Added

2020-11-19 13:06 UTC, KaterinaWire commented on Sources/Helpers/FeatureConfiguration/FeatureController.swift
> +    public static let needsToUpdateFeatureNotificationName = Notification.Name("needsToUpdateFeatureConfiguration")
Changed

2020-11-19 13:07 UTC, KaterinaWire commented on Sources/Helpers/FeatureConfiguration/FeatureController.swift
> +    }
No

2020-11-19 13:07 UTC, KaterinaWire commented on Sources/Helpers/FeatureConfiguration/Configurations.swift
> +public struct AllFeatureConfigsResponse: Decodable {
No

2020-11-19 13:08 UTC, KaterinaWire commented on Sources/Helpers/FeatureConfiguration/Configurations.swift
> +public struct FeatureConfigResponse<T: Configurable>: Decodable {
No

2020-11-19 13:13 UTC, johnxnguyen approved these changes

2020-11-19 13:28 UTC, merged