[Chore] Re-sync moved files
wireapp/wire-ios-request-strategy pull request #302
Opened 2021-05-13 21:32 UTC by KaterinaWire

## What's new in this PR?

Re-sync all moved files from SE.

2021-05-14 08:12 UTC, typfel requested changes

2021-05-14 08:12 UTC, typfel commented on Sources/Notifications/Push Notifications/Notification Types/Content/ZMLocalNotification.swift
> +/// TODO Katerina to fix calling state
Can't you restore the `.incomingCall(video: Bool)` logic I added?

2021-05-14 08:12 UTC, typfel commented on Sources/Synchronization/Decoding/EventDecoderTest.swift
> -//    fileprivate func payloadForMessage(in conversation: ZMConversation?,
This should be deleted? Doesn't exist in develop on `wire-ios-sync-engine`.

2021-06-02 15:48 UTC, KaterinaWire commented on Sources/Synchronization/Decoding/EventDecoderTest.swift
> -//    fileprivate func payloadForMessage(in conversation: ZMConversation?,
Yes. I copied `EventDecoderTest` from develop on `wire-ios-sync-engine`.
These 2 methods are in the `MessagingTestBase` extension here, and in the `MessagingTest`  on `wire-ios-sync-engine`

2021-06-02 15:50 UTC, KaterinaWire commented on Sources/Synchronization/Decoding/EventDecoderTest.swift
> -//    fileprivate func payloadForMessage(in conversation: ZMConversation?,
Yes. I copied `EventDecoderTest` from develop on `wire-ios-sync-engine`.
These 2 methods are in the `MessagingTestBase` extension here, and in the `MessagingTest` on `wire-ios-sync-engine`

2021-06-02 16:17 UTC, KaterinaWire commented on Sources/Notifications/Push Notifications/Notification Types/Content/ZMLocalNotification.swift
> +/// TODO Katerina to fix calling state
There is no `.incomingCall(video: Bool)` for `LocalNotificationType` in `wire-ios-sync-engine `now.

2021-06-07 14:19 UTC, typfel approved these changes

2021-06-11 15:43 UTC, David-Henner commented on Sources/Notifications/Push Notifications/Notification Types/LocalNotificationContentType.swift
> -        case .text, .edited:
should the `.edited` case be handled somewhere else?

2021-06-22 16:14 UTC, KaterinaWire commented on Sources/Notifications/Push Notifications/Notification Types/LocalNotificationContentType.swift
> -        case .text, .edited:
Looks like no. This was recently changed in SE. The commit comment says:
`Don't generate notifications for edit messages `

2021-06-22 16:14 UTC, KaterinaWire commented on Sources/Notifications/Push Notifications/Notification Types/LocalNotificationContentType.swift
> -        case .text, .edited:
Looks like no. This was recently changed in SE. The commit comment says:
`Don't generate notifications for edit messages`

2021-06-24 09:33 UTC, David-Henner approved these changes

2021-06-24 09:39 UTC, merged