[Fix] Notify that user cannot send a message because one of the devices doesn't support LH
wireapp/wire-ios-request-strategy pull request #317
Opened 2021-06-29 11:57 UTC by KaterinaWire

## What's new in this PR?

### Issues
When a user who is under LH has one of the devices that doesn't support LH (not updated client), there's an 412 error from BE and the user is unable to send a message.

### Causes
All clients are not updated.

### Solutions
Handle the `412` error with `"missing-legalhold-consent"` label and notify the user.

## Notes
https://wearezeta.atlassian.net/browse/SQSERVICES-526

2021-06-30 08:17 UTC, johnxnguyen requested changes
It would be good to add a test that the notification is sent.

2021-06-30 08:17 UTC, johnxnguyen commented on Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift
> +        }
Suggestion to clean this up a little: 

```swift
if response.httpStatus == 412 && response.payloadLabel() == "missing-legalhold-consent" {
  managedObjectContext.zm_userInterface.performGroupedBlock { [weak self] in
    guard let context = self?.managedObjectContext.notificationContext else { return }
    NotificationInContext(name: ZMConversation.failedToSendMessageNotificationName, context: context).post()
  }
}
```

2021-06-30 14:23 UTC, typfel commented
Is there any specs for how this should behave? I'm asking because the `ClientMessageTranscoder` is not the only place where you can receive this error.

ClientMessageTranscoder
AssetClientMessageRequestStrategy
LinkPreviewUploadRequestStrategy
GenericMessageRequestStrategy which is used in CallingRequestStrategy, AvailabilityRequestStrategy, DeliveryReceiptRequestStrategy

All send encrypted messages which can then in theory receive this error.

I guess mostly when sense show the alert when the user initiates the message sending and not when a delivery receipt is sent but that's up for discussion I guess.

2021-07-01 11:21 UTC, KaterinaWire commented
> LinkPreviewUploadRequestStrategy

We have only this ticket https://wearezeta.atlassian.net/browse/SQSERVICES-524. 
I agree that it should cover sending not only a text message, but assets as well.

About the `LinkPreviewUploadRequestStrategy`, we won't trigger it as the message will not be sent. Correct?
The calling is not a part of this task, but I will add this question to the parent ticket, because it's relevant to other platforms.

So, as I understand it, only 2 strategies (ClientMessageTranscoder, AssetClientMessageRequestStrategy) are required to handle this error. @typfel  Are you agree?

2021-07-01 11:21 UTC, KaterinaWire commented on Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift
> +        }
Done

2021-08-11 13:09 UTC, johnxnguyen approved these changes

2021-08-12 07:23 UTC, typfel approved these changes

2021-08-12 07:53 UTC, KaterinaWire commented
@zenkins release minor

2021-08-12 07:54 UTC, merged