[Feature] Add actions for joining conversation with key and code
wireapp/wire-ios-request-strategy pull request #409
Opened 2021-11-09 09:10 UTC by sb88k

## What's new in this PR?

Adding an action handler for joining conversation

## Dependencies

- https://github.com/wireapp/wire-ios-data-model/pull/1267

2021-11-09 10:04 UTC, typfel requested changes

2021-11-09 10:04 UTC, typfel commented on Sources/Request Strategies/Conversation/Actions/JoinActionHandlerTests.swift
> +final class JoinActionHandlerTests: MessagingTestBase {
Let's add a test for the error code / label mapping. 

An example of a similar test can be found here https://github.com/wireapp/wire-ios-request-strategy/blob/f1d0ab559a0d146f4a5dd35d6f6515e8d4ec5945/Sources/Request%20Strategies/Connection/Actions/ConnectToUserActionHandlerTests.swift#L76

2021-11-09 17:38 UTC, KaterinaWire commented on Cartfile.resolved
> +>>>>>>> 7517667 (apply suggestions)
```suggestion
github "wireapp/wire-ios-data-model" "feature/join-conversation-action-handler-SQCORE-1134"

```

2021-11-09 17:42 UTC, KaterinaWire commented on Cartfile.resolved
> +>>>>>>> 7517667 (apply suggestions)
I think it was left after the merging. Should be:
github "wireapp/wire-ios-data-model" "feature/join-conversation-action-handler-SQCORE-1134"

2021-11-10 13:30 UTC, sb88k commented on Sources/Request Strategies/Conversation/Actions/JoinActionHandler.swift
> +                let conversationID = event.payload["conversation"] as? String
Done

2021-11-15 22:35 UTC, KaterinaWire commented on Sources/Request Strategies/Conversation/Actions/JoinConversationActionHandlerTests.swift
> +            let response = ZMTransportResponse(payload: nil, httpStatus: 200, transportSessionError: nil)
But the error code in the name of the test is 204. This test should fail.

2021-11-15 22:39 UTC, KaterinaWire commented on Sources/Request Strategies/Conversation/Actions/JoinConversationActionHandler.swift
> +
An extra empty line

2023-09-25 19:48 UTC, closed without merging