fix: SwiftLint warnings in Source Part 3
wireapp/wire-ios-request-strategy pull request #442
Opened 2021-12-02 10:15 UTC by agisilaos

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [ ] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

In this PR I fix warnings related to the SwiftLint rules below and a warning from the Swift Compiler:

- **Vertical Parameter Alignment Violation**: Function parameters should be aligned vertically if they're in multiple lines in a declaration. `(vertical_parameter_alignment)`
- **Computed Accessors Order Violation**: Computed properties should declare first the getter and then the setter. `(computed_accessors_order)`
- **Operator Function Whitespace Violation**: Operators should be surrounded by a single whitespace when defining them. `(operator_whitespace)`
- **Duplicate Imports Violation**: Imports should be unique. `(duplicate_imports)`
- **Colon Violation**: Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. `(colon)`
- **Implicit Getter Violation**: Computed read-only properties should avoid using the get keyword. `(implicit_getter)`
- Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2021-12-02 10:17 UTC, agisilaos commented on Sources/Protocols/OTREntity.swift
>              if !missingClients.intersection(recipientClients).isEmpty {
Not sure how to fix this warning so any help is much appreciated.

2021-12-02 10:41 UTC, agisilaos commented on Sources/Protocols/OTREntity.swift
> +            if !missingClients.isDisjoint(with: recipientClients) {
Not sure if this is the correct fix for the warning. Let me know what you think.

2021-12-02 11:26 UTC, johnxnguyen requested changes

2021-12-02 11:26 UTC, johnxnguyen commented on Sources/Protocols/OTREntity.swift
> +            if !missingClients.isDisjoint(with: recipientClients) {
It's correct, but no need for the additional comment.

2021-12-03 07:27 UTC, johnxnguyen approved these changes

2021-12-21 09:29 UTC, David-Henner approved these changes

2021-12-21 09:35 UTC, merged