feat: Use the mapping methods for access roles, for the separation of access controls for guests and services SQSERVICES-1052
wireapp/wire-ios-request-strategy pull request #487
Opened 2022-02-11 14:37 UTC by agisilaos

<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1052" title="SQSERVICES-1052" target="_blank"><img alt="Story" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10815?size=medium" />SQSERVICES-1052</a>  [iOS] Separate access controls for guests and services
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

The mapping methods created in [DM](https://github.com/wireapp/wire-ios-data-model/pull/1342)  need to be used here so we can have a fall back mechanism depending of the accessRole (new or old). 

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-02-11 14:52 UTC, johnxnguyen requested changes
it'd be good to have tests for these changes.

2022-02-11 14:52 UTC, johnxnguyen commented on Sources/Payloads/Processing/PayloadProcessing+Conversation.swift
> +        }
```suggestion
          } else if let accessRole = accessRole, let legacyAccessRole = ConversationAccessRole(rawValue) {
              let accessRoles = ConversationAccessRoleV2.fromLegacyAccessRole(legacyAccessRole)
              conversation.updateAccessStatus(accessModes: accessModes, accessRoles: accessRoles.map(\.rawValue))
          }
        }
```

2022-02-11 14:52 UTC, johnxnguyen commented on Sources/Payloads/Processing/PayloadProcessing+Conversation.swift
> +        }
I think you want to check first if `data.accessRoleV2` exists, then if it doesn't, check `data.accessRole`.

2022-02-14 14:50 UTC, johnxnguyen requested changes
Don't forget to add tests for this new logic.

2022-02-14 14:50 UTC, johnxnguyen commented on Sources/Payloads/Processing/PayloadProcessing+Conversation.swift
> +                let accessRoles = ConversationAccessRoleV2.fromLegacyAccessRole(ConversationAccessRole(rawValue: accessRole) ?? .team)
It would be an error if we couldn't create `ConversationAccessRole` from a raw value, so I suggest to bind the optional value  in the `else if`:

```swift
} else if let accessRole = accessRole, let legacyAccessRole = ConversationAccessRole(rawValue: accessRole) {
...
}
```

2022-02-14 14:50 UTC, johnxnguyen commented on Sources/Payloads/Processing/PayloadProcessing+Conversation.swift
> +        } else if let accessRole = data.accessRole {
Same here.

2022-02-15 13:20 UTC, johnxnguyen requested changes
I think we're also missing tests when processing the conversation update event.

2022-02-15 13:20 UTC, johnxnguyen commented on Sources/Payloads/Processing/PayloadProcessing+ConversationTests.swift
> +            XCTAssertEqual(self.groupConversation.accessRole, accessRole)
To test the mapping from legacy to V2 we asserted that when a payload with the legacy access role is received, then it maps to V2 when using that payload to update the conversation. 

To test the other direction, we want to test that given we have a conversation with certain `accessRoles`, when we create a payload for the upstream request, then that payload contains entries for both the V2 access roles and the legacy access roles.

2022-02-15 13:20 UTC, johnxnguyen commented on Sources/Payloads/Processing/PayloadProcessing+ConversationTests.swift
> +    func testThatItMapsFromLegacyAccessRoleToAccessRoleV2() throws {
I'd also like to see a variation of this test where given the payload has V2 access roles, then it updates the conversation accordingly.

2022-02-15 14:05 UTC, agisilaos commented
> I think we're also missing tests when processing the conversation update event.

These are going to be in SE, as we discussed @johnxnguyen

2022-02-15 14:10 UTC, johnxnguyen requested changes
We still need tests for the conversation update event.

2022-02-15 15:32 UTC, johnxnguyen approved these changes

2022-02-15 15:54 UTC, KaterinaWire approved these changes

2022-02-15 17:30 UTC, merged