feat(mls): added FetchGroupStateActionHandler FS-958
wireapp/wire-ios-request-strategy pull request #576
Opened 2022-10-18 09:59 UTC by ghuMustafa

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

### Issues

_Briefly describe the issue you have solved or implemented with this pull request. If the PR contains multiple issues, use a bullet list._

### Causes (Optional)

_Briefly describe the causes behind the issues. This could be helpful to understand the adopted solutions behind some nasty bugs or complex issues._

### Solutions

_Briefly describe the solutions you have implemented for the issues explained above._

### Dependencies (Optional)

_If there are some other pull requests related to this one (e.g. new releases of frameworks), specify them here._

Needs releases with:

- [ ] GitHub link to other pull request

### Testing

#### Test Coverage (Optional)

- [ ] I have added automated test to this contribution

#### How to Test

_Briefly describe how this change was tested and if applicable the exact steps taken to verify that it works as expected._

### Notes (Optional)

_Specify here any other facts that you think are important for this issue._

### Attachments (Optional)

_Attachments like images, videos, etc. (drag and drop in the text box)_

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [ ] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

2022-10-18 09:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wireapp/wire-ios-request-strategy?pullRequest=576) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wireapp/wire-ios-request-strategy?pullRequest=576) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wireapp/wire-ios-request-strategy?pullRequest=576) it.</sub>

2022-10-20 08:45 UTC, David-Henner commented on Sources/Request Strategies/MLS/Actions/FetchPublicGroupStateActionHandler.swift
> +                action.notifyResult(.failure(.malformedResponse))
```suggestion
                action.fail(with: .malformedResponse)
```

2022-10-24 11:36 UTC, ghuMustafa commented on Sources/Request Strategies/MLS/Actions/FetchPublicGroupStateActionHandler.swift
> +                action.notifyResult(.failure(.malformedResponse))
changed.

2022-11-01 08:48 UTC, johnxnguyen commented on Sources/Request Strategies/MLS/Actions/FetchPublicGroupStateActionHandler.swift
> +            path: "/conversations/\(action.domain)/\(action.conversationId)/groupinfo",
As I mentioned in the other PR, I think we should have the conversation ID as a UUID here and map it to a string when building the request.

2022-11-03 15:59 UTC, ghuMustafa commented on Sources/Request Strategies/MLS/Actions/FetchPublicGroupStateActionHandler.swift
> +            path: "/conversations/\(action.domain)/\(action.conversationId)/groupinfo",
Yes I have conversationId as UUID

2022-11-14 09:30 UTC, johnxnguyen requested changes

2022-11-14 09:30 UTC, johnxnguyen commented on Sources/Request Strategies/MLS/Actions/FetchPublicGroupStateActionHandler.swift
> +            path: "/conversations/\(action.domain)/\(action.conversationId.uuidString)/groupinfo",
Actually I think we need to make this `action.conversationId.transportString()`

2022-11-16 14:51 UTC, David-Henner approved these changes

2022-11-17 09:53 UTC, johnxnguyen approved these changes

2022-11-23 15:36 UTC, David-Henner commented on Cartfile.resolved
> +github "wireapp/wire-ios-data-model" "feat/mls-fetch-public-group-state"
```suggestion
github "wireapp/wire-ios-data-model" "feat/mls"
```

2022-11-23 15:36 UTC, merged